Wrapper for slider 'favourites movies'
oleksandrstarov/sigma_js_internship_2021 pull request #127
Opened 2021-04-13 16:54 UTC by solomiia-sahala

-created wrapper for favourites movies to render movies in slider;
-connected axios;

2021-04-13 18:43 UTC, Dmytro1991ua approved these changes

2021-04-13 18:43 UTC, Dmytro1991ua commented on src/components/WrapperFavorites.tsx
> +import api from 'src/service/api';
Please use relative import, as done in other places (other imports) => import api from '../service/api'

2021-04-13 19:16 UTC, Kachyr commented on package.json
> +}
add newline

2021-04-13 19:24 UTC, oleksandrstarov requested changes
It seems to be some extra changes in this PR, can you check please?

2021-04-13 19:25 UTC, Kachyr commented on src/App.tsx
> -            <Route path="/search-results" component={SearchResults} />
Strange, wasn't it already on the main branch?

2021-04-13 19:25 UTC, Kachyr commented on src/axios/url.tsx
> +export default url;
add newline

2021-04-13 19:26 UTC, Kachyr commented on src/components/Favorites.tsx
> +export default Favorites;
add newline

2021-04-13 19:30 UTC, Kachyr commented on src/components/SmallInfoCard.tsx
> +      </link> */}
Thats a lot of commented code

2021-04-13 19:32 UTC, Kachyr commented on src/constants/api.tsx
> +export const API_DATE_QUERY = 'primary_release_date.lte=';
add newline

2021-04-13 19:32 UTC, Kachyr commented on src/service/api.tsx
> +export default api;
newline

2021-04-13 19:32 UTC, Kachyr commented on src/styles/Breadcrumbs.scss
> +}
add newline

2021-04-13 19:32 UTC, Kachyr commented on src/styles/Detail.scss
> +}
add newline

2021-04-13 19:33 UTC, Kachyr commented on src/styles/Header.scss
> +}
add newline

2021-04-13 19:34 UTC, Kachyr commented on src/styles/SmallCardInfo.scss
> +}
add newline

2021-04-13 19:37 UTC, Kachyr reviewed
check coments

2021-04-14 17:55 UTC, oleksandrstarov approved these changes
Looks good, nice work!
Check comments

2021-04-14 17:55 UTC, oleksandrstarov commented on src/components/WrapperFavorites.tsx
> +          {movieInfo.map((movie: MovieId) => {
(movie: MovieId) >> ({ id }: MovieId) so less code :)

2021-04-14 17:55 UTC, oleksandrstarov commented on src/components/WrapperFavorites.tsx
> +  return (!movieInfo.length ? null : (
it is nicer to have check 
if(!movieInfo.length) {
return null;
}

return (markup)

2021-04-14 17:55 UTC, oleksandrstarov commented on src/App.scss
> +
Cant really find where this is used....

2021-04-14 18:42 UTC, merged