Feature/service pagination
oleksandrstarov/sigma_js_internship_2021 pull request #132
Opened 2021-04-14 18:49 UTC by mrSelieznov

#129 Task

- Updated API methods to use pagination
- Added method to change response without api's pages pagination to custom
- Updated manual service

2021-04-15 15:15 UTC, oleksandrstarov requested changes

2021-04-15 15:15 UTC, oleksandrstarov commented on src/service/api.tsx
> +    const obj = await axios.get(`movie/popular?${API_KEY}&query&page=${page}`);
&query& ???

2021-04-15 15:15 UTC, oleksandrstarov commented on src/service/api.tsx
> +  changeListByPagination(arr: Array<{}>, page: number = 1) {
where is return type? Array<{}> - is wrong... here you might use generics - https://www.typescriptlang.org/docs/handbook/2/generics.html
`changeListByPagination(arr: Array<T>, page: number = 1): Array<T> {`

2021-04-15 15:15 UTC, oleksandrstarov commented on src/service/api.tsx
> +      ? arr.slice(0, 20)
maybe just arr? why slice?

2021-04-15 20:28 UTC, mrSelieznov commented on src/service/api.tsx
> +      ? arr.slice(0, 20)
oh yes you are right

2021-04-16 07:25 UTC, oleksandrstarov requested changes

2021-04-16 07:25 UTC, oleksandrstarov commented on src/service/api.tsx
> +  },
Already left comment for this code
add types 
Array<T>
{}[] - is NOT a valid type

2021-04-16 07:27 UTC, oleksandrstarov commented on src/service/api.tsx
> +  changeListByPagination(arr: Array<{}>, page: number = 1) {
have you seen this comment @mrSelieznov it is as easy as ctrl+c > ctrl+v as solution already here

2021-04-16 12:15 UTC, oleksandrstarov requested changes

2021-04-16 12:15 UTC, oleksandrstarov commented on src/service/api.tsx
> +    return !store.includes(id);
wrong condition, if Id in history it should include

2021-04-16 12:37 UTC, oleksandrstarov approved these changes

2021-04-19 09:34 UTC, merged