Added pagination
oleksandrstarov/sigma_js_internship_2021 pull request #195
Opened 2021-04-22 23:23 UTC by di-shu

2021-04-23 05:12 UTC, Dmytro1991ua reviewed
LGTM

2021-04-23 15:35 UTC, oleksandrstarov requested changes
Check build status and fix comment

2021-04-23 15:35 UTC, oleksandrstarov commented on src/service/api.tsx
> +    let obj = await axios.get(`search/movie?${API_KEY}&query=${query}&page=${page}`);
Why let?

2021-04-25 17:04 UTC, oleksandrstarov approved these changes
LGTM

2021-04-26 14:19 UTC, AnnaBolshak commented
Could you check please, if add some movie to favourites and goto favourites page - there is the error in this branch 
![image](https://user-images.githubusercontent.com/35143261/116098177-84a9a800-a6b3-11eb-84ff-4a035be8b21e.png)

2021-04-26 14:49 UTC, merged