fexed rendere comppnents
oleksandrstarov/sigma_js_internship_2021 pull request #208
Opened 2021-04-23 15:19 UTC by mrSelieznov

#207 Task

Updated render results component for delivery page

2021-04-23 16:25 UTC, Dmytro1991ua approved these changes

2021-04-23 17:54 UTC, solomiia-sahala commented on src/styles/CardInfo.scss
> +      // flex-direction: column-reverse;
remove commented lines pls

2021-04-23 17:55 UTC, solomiia-sahala commented on src/styles/CardInfo.scss
> +
remove empty line pls

2021-04-23 17:57 UTC, solomiia-sahala requested changes

2021-04-23 17:57 UTC, solomiia-sahala commented on src/styles/CardInfo.scss
> +
remove line pls

2021-04-23 17:57 UTC, solomiia-sahala commented on src/styles/CardInfo.scss
> +  width: 580pxpx;
double "px"

2021-04-24 10:18 UTC, oleksandrstarov requested changes

2021-04-24 10:18 UTC, oleksandrstarov commented on src/styles/CardInfo.scss
> +.big-card{
add space before {

2021-04-24 13:46 UTC, oleksandrstarov commented
fexed rendere comppnents you have misspelled all words in RP name...

2021-04-24 13:49 UTC, oleksandrstarov approved these changes
Check comments please

2021-04-24 13:49 UTC, oleksandrstarov commented on src/styles/CardInfo.scss
> +%pos-absolute-left0  {
why you added 2 spaces?

2021-04-24 13:49 UTC, oleksandrstarov commented on src/styles/CardInfo.scss
> +%stretch  {
same

2021-04-24 13:49 UTC, oleksandrstarov commented on src/styles/CardInfo.scss
> +%area-card  {
same

2021-04-24 13:49 UTC, oleksandrstarov commented on src/styles/CardInfo.scss
> +  @media screen and(max-width: 630px)  {
all above are same - 2 spaces...

2021-04-26 08:58 UTC, Kachyr approved these changes

2021-04-26 09:33 UTC, solomiia-sahala approved these changes

2021-04-26 09:34 UTC, merged