added last seens to layout
oleksandrstarov/sigma_js_internship_2021 pull request #210
Opened 2021-04-23 16:20 UTC by mrSelieznov

#209 Task

Add last seens to layout

2021-04-23 16:25 UTC, Dmytro1991ua approved these changes

2021-04-23 18:02 UTC, solomiia-sahala approved these changes

2021-04-24 10:17 UTC, oleksandrstarov requested changes

2021-04-24 10:17 UTC, oleksandrstarov commented on src/config/routing.tsx
> +    path: '/LastSeen/:page',
as a rule path should be kebab-case check how other path looks like

2021-04-25 17:03 UTC, oleksandrstarov requested changes

2021-04-25 17:03 UTC, oleksandrstarov commented on src/config/routing.tsx
> +    name: 'LastSeen',
Please align name style with existing name styles. It is separate words

2021-04-27 07:29 UTC, oleksandrstarov commented on src/config/routing.tsx
> +      '/search-results/:title?/:genre?/:fromYear?/:toYear?/:favorites?/:favorites?/:page',
I think it is not relevant - the path was changed. Can you confirm?

2021-04-27 07:29 UTC, oleksandrstarov approved these changes

2021-04-27 10:21 UTC, merged