Feature/button render results
oleksandrstarov/sigma_js_internship_2021 pull request #216
Opened 2021-04-23 17:19 UTC by mrSelieznov

#215 Task
Updated

2021-04-23 18:09 UTC, solomiia-sahala commented on src/components/RenderResults.tsx
> +      <div className="view-toggler ">
remove extra space inside class

2021-04-23 18:09 UTC, solomiia-sahala approved these changes

2021-04-24 10:05 UTC, oleksandrstarov requested changes
This seems to be duplicated in Feature/update cardinfo with favorite

2021-04-24 10:05 UTC, oleksandrstarov commented on src/styles/RenderResults.scss
> +
remove empty line

2021-04-24 13:45 UTC, oleksandrstarov approved these changes

2021-04-24 15:49 UTC, merged