Feature/update cardinfo with favorite
oleksandrstarov/sigma_js_internship_2021 pull request #218
Opened 2021-04-23 17:41 UTC by mrSelieznov

#217 Task

Added favorite button to info card

2021-04-23 18:10 UTC, solomiia-sahala approved these changes

2021-04-23 18:19 UTC, Dmytro1991ua approved these changes

2021-04-24 10:03 UTC, oleksandrstarov requested changes
Would be nice is you pay a little more attention while creating PR

2021-04-24 10:03 UTC, oleksandrstarov commented on src/styles/RenderResults.scss
> +
Remove empty line

2021-04-24 10:03 UTC, oleksandrstarov commented on src/styles/CardInfo.scss
> +.info-card-activities-mobile{
add space before {

2021-04-24 10:03 UTC, oleksandrstarov commented on src/components/RenderResults.tsx
> +      <div className="view-toggler ">
remove space

2021-04-24 13:45 UTC, oleksandrstarov commented on src/styles/CardInfo.scss
> + left: 0;
please check all your changes for styles and add indent inside blocks

2021-04-24 13:45 UTC, oleksandrstarov commented on src/styles/CardInfo.scss
> + background-color: $white;
should be 2 spaces

2021-04-27 07:30 UTC, oleksandrstarov approved these changes

2021-04-27 10:21 UTC, merged