Feature/wrapper history
oleksandrstarov/sigma_js_internship_2021 pull request #227
Opened 2021-04-25 19:21 UTC by mrSelieznov

#226 Task

added wrapper component

//add after service/context/ component set. bar

2021-04-25 19:30 UTC, mrSelieznov reviewed
So mach files due to prettier

2021-04-25 19:42 UTC, oleksandrstarov requested changes
Nice refactoring, but please check your own code before creating PR

2021-04-25 19:42 UTC, oleksandrstarov commented on src/components/Home.tsx
> +import { useEffect, useState } from "react";
use single quotes

2021-04-25 19:42 UTC, oleksandrstarov commented on src/components/RenderResults.tsx
> +import { useState } from "react";
Use single quotes

2021-04-25 19:42 UTC, oleksandrstarov commented on src/components/RenderResults.tsx
> +      <div className="view-toggler ">
remove empty space

2021-04-27 07:36 UTC, oleksandrstarov approved these changes
Fix comments

2021-04-27 07:36 UTC, oleksandrstarov commented on src/components/WrapperLastSeen.tsx
> +
Remove line

2021-04-27 07:36 UTC, oleksandrstarov commented on src/components/WrapperLastSeen.tsx
> +type MovieId = {
I remember I left comment regarding such type - we have one same  already and can reuse it

2021-04-27 11:21 UTC, merged