Feature/wrapper popular
oleksandrstarov/sigma_js_internship_2021 pull request #229
Opened 2021-04-25 20:17 UTC by mrSelieznov

#228 Task

Add popular wrapper for home

// add after service, context, component bar

2021-04-25 20:19 UTC, mrSelieznov reviewed
Added wrapper popular, other due to prettier

2021-04-26 10:39 UTC, oleksandrstarov requested changes

2021-04-26 10:39 UTC, oleksandrstarov commented on src/components/Home.tsx
> +import WrapperFavorites from "./WrapperFavorites";
Use single quotes

2021-04-26 10:39 UTC, oleksandrstarov commented on src/components/WrapperPopular.tsx
> +type MovieId = {
WrapperFavorites already has such type - no need to clone it

2021-04-26 10:39 UTC, oleksandrstarov commented on src/components/WrapperPopular.tsx
> +  const [movies, setMovies] = useState<[]>([]);
`<[]>` is not a valid type

2021-04-27 07:38 UTC, oleksandrstarov requested changes

2021-04-27 07:38 UTC, oleksandrstarov commented on src/components/WrapperPopular.tsx
> +type MoviesDataType = [];
this is not a valid type still

2021-04-27 07:38 UTC, oleksandrstarov commented on src/components/WrapperPopular.tsx
> +  const [movies, setMovies] = useState<MoviesDataType>([]);
Should be type <Array<MoviesId>>

2021-04-27 10:58 UTC, oleksandrstarov approved these changes

2021-04-27 11:06 UTC, merged