Feature/render results title
oleksandrstarov/sigma_js_internship_2021 pull request #231
Opened 2021-04-25 20:41 UTC by mrSelieznov

#230 Task

Added title for render results

2021-04-25 20:45 UTC, mrSelieznov reviewed
I set 'viewed' all files changed by prettier and leave empty my changes

2021-04-26 10:35 UTC, oleksandrstarov requested changes

2021-04-26 10:35 UTC, oleksandrstarov commented on src/components/Home.tsx
> +import { useEffect, useState } from "react";
Use single quotes

2021-04-26 10:35 UTC, oleksandrstarov commented on src/components/RenderResults.tsx
> +import { useState } from "react";
Use single quotes

2021-04-26 12:17 UTC, oleksandrstarov requested changes

2021-04-26 12:17 UTC, oleksandrstarov commented on src/styles/RenderResults.scss
> +  display: flex;
check indent for this block

2021-04-26 12:17 UTC, oleksandrstarov commented on src/components/Home.tsx
> +import api from "src/service/api";
Use single quotes

2021-04-26 15:23 UTC, oleksandrstarov approved these changes

2021-04-27 07:40 UTC, oleksandrstarov approved these changes

2021-04-27 07:48 UTC, Kachyr approved these changes

2021-04-27 10:47 UTC, merged